import { NetworkConnection, LocalOrigin, LivePacket } from '../types/network';

export const LOCAL_ORIGIN: LocalOrigin = {
  name: 'Local Node (Client Gateway)',
  ip: '192.168.1.108',
  city: 'Frankfurt am Main',
  country: 'Deutschland',
  countryCode: 'DE',
  lat: 50.1109,
  lng: 8.6821,
  isp: 'Deutsche Telekom AG / AS3320',
};

export const INITIAL_CONNECTIONS: NetworkConnection[] = [
  {
    id: 'conn-fra-cf',
    name: 'Cloudflare Anycast Edge',
    host: 'one.one.one.one',
    ip: '1.1.1.1',
    port: 443,
    protocol: 'DNS',
    type: 'dns',
    city: 'Frankfurt',
    country: 'Deutschland',
    countryCode: 'DE',
    lat: 50.1109,
    lng: 8.6821,
    status: 'active',
    latencyMs: 4.8,
    jitterMs: 0.4,
    rxKbps: 420.5,
    txKbps: 110.2,
    packetLossRate: 0.0,
    totalPackets: 48920,
    encryption: {
      protocol: 'DoH / TLS 1.3',
      cipher: 'TLS_AES_128_GCM_SHA256',
      certIssuer: 'Cloudflare Inc ECC CA-3',
      certValidDays: 240,
    },
    whois: {
      asn: 'AS13335',
      asnOrg: 'Cloudflare, Inc.',
      netName: 'CLOUDFLARENET',
      cidr: '1.1.1.0/24',
      registrar: 'APNIC / RIPE NCC',
      registeredDate: '2011-08-11',
      updatedDate: '2025-01-14',
      abuseContact: 'abuse@cloudflare.com',
      reputationScore: 99.4,
      dnsServers: ['ns1.cloudflare.com', 'ns2.cloudflare.com'],
      orgAddress: '101 Townsend St, San Francisco, CA 94107, USA',
      statusComment: 'Global Low-Latency Public DNS Resolver Cluster',
    },
    tracerouteHops: [
      { hopNumber: 1, ip: '192.168.1.1', hostname: 'fritz.box', latencyMs: 0.8, carrier: 'LAN Gateway', location: 'Local', status: 'ok' },
      { hopNumber: 2, ip: '62.155.242.74', hostname: 'f-ed5-i.F.DE.NET.DTAG.DE', latencyMs: 2.1, carrier: 'Deutsche Telekom', location: 'Frankfurt', status: 'ok' },
      { hopNumber: 3, ip: '80.150.170.8', hostname: 'de-cix-frankfurt.cloudflare.com', latencyMs: 3.4, carrier: 'DE-CIX Peering', location: 'Frankfurt IX', status: 'ok' },
      { hopNumber: 4, ip: '1.1.1.1', hostname: 'one.one.one.one', latencyMs: 4.8, carrier: 'Cloudflare Anycast', location: 'Frankfurt Edge', status: 'ok' },
    ],
  },
  {
    id: 'conn-ams-fastly',
    name: 'Fastly CDN Edge Cache',
    host: 'prod.fastly.net',
    ip: '151.101.65.140',
    port: 443,
    protocol: 'HTTPS',
    type: 'cdn',
    city: 'Amsterdam',
    country: 'Niederlande',
    countryCode: 'NL',
    lat: 52.3676,
    lng: 4.9041,
    status: 'active',
    latencyMs: 12.4,
    jitterMs: 0.9,
    rxKbps: 1850.0,
    txKbps: 340.8,
    packetLossRate: 0.0,
    totalPackets: 81200,
    encryption: {
      protocol: 'HTTP/3 / QUIC (TLS 1.3)',
      cipher: 'TLS_CHACHA20_POLY1305_SHA256',
      certIssuer: 'Let\'s Encrypt Authority X3',
      certValidDays: 62,
    },
    whois: {
      asn: 'AS54113',
      asnOrg: 'Fastly Inc.',
      netName: 'FASTLY-AMSTERDAM',
      cidr: '151.101.0.0/16',
      registrar: 'ARIN',
      registeredDate: '2014-03-20',
      updatedDate: '2024-11-09',
      abuseContact: 'noc-abuse@fastly.com',
      reputationScore: 98.9,
      dnsServers: ['a.rt.fastly.net', 'b.rt.fastly.net'],
      orgAddress: '475 Brannan St #300, San Francisco, CA, USA',
      statusComment: 'Edge Cloud Platform POP - AMS-IX Interconnected',
    },
    tracerouteHops: [
      { hopNumber: 1, ip: '192.168.1.1', hostname: 'fritz.box', latencyMs: 0.9, carrier: 'LAN Gateway', location: 'Local', status: 'ok' },
      { hopNumber: 2, ip: '62.155.242.74', hostname: 'f-ed5-i.F.DE.NET.DTAG.DE', latencyMs: 2.3, carrier: 'Deutsche Telekom', location: 'Frankfurt', status: 'ok' },
      { hopNumber: 3, ip: '217.5.98.114', hostname: 'ams-s2-rou-1002.NL.eurorings.net', latencyMs: 8.6, carrier: 'KPN EuroRings', location: 'Düsseldorf / Arnhem', status: 'ok' },
      { hopNumber: 4, ip: '80.249.208.23', hostname: 'ams-ix.fastly.net', latencyMs: 11.2, carrier: 'AMS-IX Node', location: 'Amsterdam Science Park', status: 'ok' },
      { hopNumber: 5, ip: '151.101.65.140', hostname: 'prod.fastly.net', latencyMs: 12.4, carrier: 'Fastly Edge', location: 'Amsterdam', status: 'ok' },
    ],
  },
  {
    id: 'conn-iad-aws',
    name: 'AWS Cloud Core (us-east-1)',
    host: 'ec2.us-east-1.amazonaws.com',
    ip: '52.94.0.12',
    port: 443,
    protocol: 'gRPC',
    type: 'cloud',
    city: 'Ashburn, VA',
    country: 'Vereinigte Staaten',
    countryCode: 'US',
    lat: 39.0438,
    lng: -77.4874,
    status: 'active',
    latencyMs: 86.2,
    jitterMs: 1.8,
    rxKbps: 3420.0,
    txKbps: 1240.5,
    packetLossRate: 0.1,
    totalPackets: 124800,
    encryption: {
      protocol: 'TLS 1.3 / ALPN h2',
      cipher: 'TLS_AES_256_GCM_SHA384',
      certIssuer: 'Amazon RSA 2048 M02',
      certValidDays: 310,
    },
    whois: {
      asn: 'AS16509',
      asnOrg: 'Amazon.com, Inc.',
      netName: 'AMAZON-VA',
      cidr: '52.94.0.0/16',
      registrar: 'ARIN',
      registeredDate: '1995-05-18',
      updatedDate: '2025-02-01',
      abuseContact: 'trustandsafety@amazon.com',
      reputationScore: 99.1,
      dnsServers: ['ns-102.awsdns-12.com', 'ns-624.awsdns-14.net'],
      orgAddress: '410 Terry Ave N, Seattle, WA 98109, USA',
      statusComment: 'Equinix DC2 Hyper-scale Datacenter Campus',
    },
    tracerouteHops: [
      { hopNumber: 1, ip: '192.168.1.1', hostname: 'fritz.box', latencyMs: 0.7, carrier: 'LAN Gateway', location: 'Local', status: 'ok' },
      { hopNumber: 2, ip: '62.155.242.74', hostname: 'f-ed5-i.F.DE.NET.DTAG.DE', latencyMs: 2.2, carrier: 'Deutsche Telekom', location: 'Frankfurt', status: 'ok' },
      { hopNumber: 3, ip: '62.157.251.22', hostname: 'dtag-fra-lon.seabone.net', latencyMs: 14.5, carrier: 'Telecom Italia Sparkle', location: 'London Telehouse', status: 'ok' },
      { hopNumber: 4, ip: '213.144.176.88', hostname: 'transatlantic-cable-tgn.com', latencyMs: 72.4, carrier: 'Tata TGN Atlantic', location: 'Subsea Atlantic Cable', status: 'ok' },
      { hopNumber: 5, ip: '99.82.178.4', hostname: 'aws-border-gw-iad.amazon.com', latencyMs: 84.1, carrier: 'AWS Direct Connect', location: 'Ashburn, VA', status: 'ok' },
      { hopNumber: 6, ip: '52.94.0.12', hostname: 'ec2.us-east-1.amazonaws.com', latencyMs: 86.2, carrier: 'AWS VPC Core', location: 'Ashburn, VA', status: 'ok' },
    ],
  },
  {
    id: 'conn-sfo-github',
    name: 'GitHub Enterprise API',
    host: 'api.github.com',
    ip: '140.82.112.6',
    port: 443,
    protocol: 'WSS',
    type: 'api',
    city: 'San Francisco',
    country: 'Vereinigte Staaten',
    countryCode: 'US',
    lat: 37.7749,
    lng: -122.4194,
    status: 'active',
    latencyMs: 134.6,
    jitterMs: 2.4,
    rxKbps: 920.4,
    txKbps: 180.2,
    packetLossRate: 0.0,
    totalPackets: 32400,
    encryption: {
      protocol: 'TLS 1.3 / WebSocket Secure',
      cipher: 'TLS_AES_256_GCM_SHA384',
      certIssuer: 'DigiCert Global G2 TLS RSA SHA256 2020 CA1',
      certValidDays: 142,
    },
    whois: {
      asn: 'AS36459',
      asnOrg: 'GitHub, Inc.',
      netName: 'GITHUB',
      cidr: '140.82.112.0/20',
      registrar: 'ARIN',
      registeredDate: '2008-02-15',
      updatedDate: '2024-09-18',
      abuseContact: 'abuse@github.com',
      reputationScore: 99.7,
      dnsServers: ['dns1.p08.nsone.net', 'dns2.p08.nsone.net'],
      orgAddress: '88 Colin P Kelly Jr St, San Francisco, CA 94107, USA',
      statusComment: 'Microsoft Azure Anycast API Infrastructure',
    },
    tracerouteHops: [
      { hopNumber: 1, ip: '192.168.1.1', hostname: 'fritz.box', latencyMs: 0.8, carrier: 'LAN Gateway', location: 'Local', status: 'ok' },
      { hopNumber: 2, ip: '62.155.242.74', hostname: 'f-ed5-i.F.DE.NET.DTAG.DE', latencyMs: 2.1, carrier: 'Deutsche Telekom', location: 'Frankfurt', status: 'ok' },
      { hopNumber: 3, ip: '80.157.202.13', hostname: 'fra-cr1.telekom.de', latencyMs: 4.2, carrier: 'DTAG Core', location: 'Frankfurt', status: 'ok' },
      { hopNumber: 4, ip: '213.144.177.10', hostname: 'ny-transatlantic.seabone.net', latencyMs: 76.5, carrier: 'Level3 / Lumen', location: 'New York NY', status: 'ok' },
      { hopNumber: 5, ip: '4.68.72.10', hostname: 'chi-cr2.lumen.tech', latencyMs: 98.4, carrier: 'Lumen Backbone', location: 'Chicago IL', status: 'ok' },
      { hopNumber: 6, ip: '4.68.110.2', hostname: 'sfo-edge1.github.net', latencyMs: 132.8, carrier: 'Telia Carrier / Arelion', location: 'San Francisco CA', status: 'ok' },
      { hopNumber: 7, ip: '140.82.112.6', hostname: 'api.github.com', latencyMs: 134.6, carrier: 'GitHub Edge', location: 'San Francisco CA', status: 'ok' },
    ],
  },
  {
    id: 'conn-tyo-ntt',
    name: 'Tokyo Tier-1 Gateway',
    host: 'tyo-core.ntt.net',
    ip: '129.250.2.148',
    port: 443,
    protocol: 'QUIC',
    type: 'gateway',
    city: 'Tokio',
    country: 'Japan',
    countryCode: 'JP',
    lat: 35.6762,
    lng: 139.6503,
    status: 'active',
    latencyMs: 218.4,
    jitterMs: 3.8,
    rxKbps: 760.0,
    txKbps: 195.0,
    packetLossRate: 0.2,
    totalPackets: 29800,
    encryption: {
      protocol: 'QUIC / RFC 9000',
      cipher: 'TLS_AES_128_GCM_SHA256',
      certIssuer: 'GlobalSign Extended Validation CA',
      certValidDays: 190,
    },
    whois: {
      asn: 'AS2914',
      asnOrg: 'NTT Communications Corporation',
      netName: 'GIN-NET',
      cidr: '129.250.0.0/16',
      registrar: 'APNIC',
      registeredDate: '1992-06-03',
      updatedDate: '2024-12-19',
      abuseContact: 'gin-abuse@ntt.net',
      reputationScore: 98.5,
      dnsServers: ['ns1.gin.ntt.net', 'ns2.gin.ntt.net'],
      orgAddress: 'Granpark Tower, 3-4-1 Shibaura, Minato-ku, Tokyo, Japan',
      statusComment: 'Pacific Global IP Network Backbone Hub',
    },
    tracerouteHops: [
      { hopNumber: 1, ip: '192.168.1.1', hostname: 'fritz.box', latencyMs: 0.8, carrier: 'LAN Gateway', location: 'Local', status: 'ok' },
      { hopNumber: 2, ip: '62.155.242.74', hostname: 'f-ed5-i.F.DE.NET.DTAG.DE', latencyMs: 2.2, carrier: 'Deutsche Telekom', location: 'Frankfurt', status: 'ok' },
      { hopNumber: 3, ip: '213.198.72.6', hostname: 'ffm-b1-link.ip.twelve99.net', latencyMs: 4.8, carrier: 'Arelion Global', location: 'Frankfurt', status: 'ok' },
      { hopNumber: 4, ip: '62.115.113.120', hostname: 'ldn-b1-link.ip.twelve99.net', latencyMs: 14.1, carrier: 'Arelion Trans-Eurasia', location: 'London', status: 'ok' },
      { hopNumber: 5, ip: '62.115.122.9', hostname: 'mow-b2-link.ip.twelve99.net', latencyMs: 95.3, carrier: 'Trans-Siberian Optical', location: 'Eurasia Route', status: 'ok' },
      { hopNumber: 6, ip: '129.250.3.44', hostname: 'ae-1.gin.ntt.net', latencyMs: 212.1, carrier: 'NTT Tokyo Hub', location: 'Tokyo TY3', status: 'ok' },
      { hopNumber: 7, ip: '129.250.2.148', hostname: 'tyo-core.ntt.net', latencyMs: 218.4, carrier: 'NTT Communications', location: 'Tokyo Otemachi', status: 'ok' },
    ],
  },
  {
    id: 'conn-sin-sea',
    name: 'Singapore Equinix SG1 Hub',
    host: 'sg-edge.singtel.com',
    ip: '165.21.83.88',
    port: 443,
    protocol: 'HTTPS',
    type: 'gateway',
    city: 'Singapur',
    country: 'Singapur',
    countryCode: 'SG',
    lat: 1.3521,
    lng: 103.8198,
    status: 'active',
    latencyMs: 165.2,
    jitterMs: 1.7,
    rxKbps: 640.8,
    txKbps: 210.3,
    packetLossRate: 0.0,
    totalPackets: 19400,
    encryption: {
      protocol: 'TLS 1.3 / HTTP/2',
      cipher: 'TLS_AES_256_GCM_SHA384',
      certIssuer: 'Sectigo RSA Organization Validation',
      certValidDays: 85,
    },
    whois: {
      asn: 'AS7473',
      asnOrg: 'Singapore Telecommunications Ltd',
      netName: 'SINGTEL-IX',
      cidr: '165.21.0.0/16',
      registrar: 'APNIC',
      registeredDate: '1996-04-12',
      updatedDate: '2024-10-05',
      abuseContact: 'abuse@singtel.com',
      reputationScore: 97.8,
      dnsServers: ['ns1.singnet.com.sg', 'ns2.singnet.com.sg'],
      orgAddress: '31 Exeter Road, Comcentre, Singapore 239732',
      statusComment: 'SEA-ME-WE Subsea Cable Landing Terminal',
    },
    tracerouteHops: [
      { hopNumber: 1, ip: '192.168.1.1', hostname: 'fritz.box', latencyMs: 0.9, carrier: 'LAN Gateway', location: 'Local', status: 'ok' },
      { hopNumber: 2, ip: '62.155.242.74', hostname: 'f-ed5-i.F.DE.NET.DTAG.DE', latencyMs: 2.1, carrier: 'Deutsche Telekom', location: 'Frankfurt', status: 'ok' },
      { hopNumber: 3, ip: '80.157.204.18', hostname: 'fra-mrs-b1.dtag.net', latencyMs: 18.4, carrier: 'DTAG Mediterranean', location: 'Marseille Cable Landing', status: 'ok' },
      { hopNumber: 4, ip: '195.229.0.12', hostname: 'sea-me-we-5.transit.net', latencyMs: 92.5, carrier: 'SMW-5 Subsea System', location: 'Suez Canal / Red Sea', status: 'ok' },
      { hopNumber: 5, ip: '203.208.140.2', hostname: 'sg1-gateway.singtel.net', latencyMs: 161.4, carrier: 'Singtel Backbone', location: 'Singapore Ayer Rajah', status: 'ok' },
      { hopNumber: 6, ip: '165.21.83.88', hostname: 'sg-edge.singtel.com', latencyMs: 165.2, carrier: 'Singtel Corporate', location: 'Singapore', status: 'ok' },
    ],
  },
  {
    id: 'conn-syd-equinix',
    name: 'Sydney Trans-Pacific Relay',
    host: 'syd-peering.equinix.com',
    ip: '139.130.4.5',
    port: 443,
    protocol: 'HTTPS',
    type: 'cloud',
    city: 'Sydney',
    country: 'Australien',
    countryCode: 'AU',
    lat: -33.8688,
    lng: 151.2093,
    status: 'warning',
    latencyMs: 284.1,
    jitterMs: 5.6,
    rxKbps: 310.2,
    txKbps: 98.4,
    packetLossRate: 0.6,
    totalPackets: 15100,
    encryption: {
      protocol: 'TLS 1.2 / Extended Validation',
      cipher: 'ECDHE-RSA-AES256-GCM-SHA384',
      certIssuer: 'DigiCert TLS RSA SHA256 2020 CA1',
      certValidDays: 45,
    },
    whois: {
      asn: 'AS1221',
      asnOrg: 'Telstra Corporation Limited',
      netName: 'TELSTRA-AU',
      cidr: '139.130.0.0/16',
      registrar: 'APNIC',
      registeredDate: '1991-03-27',
      updatedDate: '2024-11-22',
      abuseContact: 'cert@telstra.com',
      reputationScore: 94.2,
      dnsServers: ['ns1.telstra.net', 'ns2.telstra.net'],
      orgAddress: '242 Exhibition St, Melbourne VIC 3000, Australia',
      statusComment: 'Southern Cross Cable Subsea Segment - High Latency',
    },
    tracerouteHops: [
      { hopNumber: 1, ip: '192.168.1.1', hostname: 'fritz.box', latencyMs: 0.8, carrier: 'LAN Gateway', location: 'Local', status: 'ok' },
      { hopNumber: 2, ip: '62.155.242.74', hostname: 'f-ed5-i.F.DE.NET.DTAG.DE', latencyMs: 2.3, carrier: 'Deutsche Telekom', location: 'Frankfurt', status: 'ok' },
      { hopNumber: 3, ip: '213.144.177.10', hostname: 'us-lax-transit.seabone.net', latencyMs: 142.1, carrier: 'Trans-Atlantic / Pacific', location: 'Los Angeles CA', status: 'ok' },
      { hopNumber: 4, ip: '139.130.200.1', hostname: 'sxc-cable-lax-syd.net', latencyMs: 270.4, carrier: 'Southern Cross Cable', location: 'Pacific Ocean Trench', status: 'degraded' },
      { hopNumber: 5, ip: '139.130.4.5', hostname: 'syd-peering.equinix.com', latencyMs: 284.1, carrier: 'Telstra Australia', location: 'Sydney Alexandria', status: 'ok' },
    ],
  },
  {
    id: 'conn-sao-telecom',
    name: 'São Paulo Latin Interconnect',
    host: 'sp-core.ix.br',
    ip: '200.219.136.1',
    port: 443,
    protocol: 'TCP',
    type: 'gateway',
    city: 'São Paulo',
    country: 'Brasilien',
    countryCode: 'BR',
    lat: -23.5505,
    lng: -46.6333,
    status: 'active',
    latencyMs: 195.7,
    jitterMs: 2.1,
    rxKbps: 520.1,
    txKbps: 140.6,
    packetLossRate: 0.1,
    totalPackets: 18700,
    encryption: {
      protocol: 'TLS 1.3 / BGP Peer Security',
      cipher: 'TLS_AES_256_GCM_SHA384',
      certIssuer: 'GlobalSign Root R3',
      certValidDays: 220,
    },
    whois: {
      asn: 'AS26162',
      asnOrg: 'NIC.br - Núcleo de Informação e Coordenação',
      netName: 'IX-BR-SP',
      cidr: '200.219.136.0/22',
      registrar: 'LACNIC',
      registeredDate: '2004-09-15',
      updatedDate: '2024-08-30',
      abuseContact: 'abuse@nic.br',
      reputationScore: 98.2,
      dnsServers: ['a.dns.br', 'b.dns.br'],
      orgAddress: 'Av. das Nações Unidas, 11541, São Paulo, Brazil',
      statusComment: 'Brazilian Internet Exchange Point - PTT Metro SP',
    },
    tracerouteHops: [
      { hopNumber: 1, ip: '192.168.1.1', hostname: 'fritz.box', latencyMs: 0.8, carrier: 'LAN Gateway', location: 'Local', status: 'ok' },
      { hopNumber: 2, ip: '62.155.242.74', hostname: 'f-ed5-i.F.DE.NET.DTAG.DE', latencyMs: 2.2, carrier: 'Deutsche Telekom', location: 'Frankfurt', status: 'ok' },
      { hopNumber: 3, ip: '80.150.170.1', hostname: 'fra-lis-seabone.net', latencyMs: 38.6, carrier: 'Sparkle Seabone', location: 'Lissabon Landing', status: 'ok' },
      { hopNumber: 4, ip: '213.144.180.5', hostname: 'ellalink-subsea-br.net', latencyMs: 172.3, carrier: 'EllaLink Subsea Cable', location: 'South Atlantic', status: 'ok' },
      { hopNumber: 5, ip: '200.219.136.1', hostname: 'sp-core.ix.br', latencyMs: 195.7, carrier: 'IX.br Metro', location: 'São Paulo', status: 'ok' },
    ],
  },
  {
    id: 'conn-cpt-teraco',
    name: 'Cape Town Africa-1 Edge',
    host: 'cpt-ixp.teraco.co.za',
    ip: '197.80.128.4',
    port: 443,
    protocol: 'HTTPS',
    type: 'cdn',
    city: 'Kapstadt',
    country: 'Südafrika',
    countryCode: 'ZA',
    lat: -33.9249,
    lng: 18.4241,
    status: 'active',
    latencyMs: 148.9,
    jitterMs: 1.5,
    rxKbps: 410.0,
    txKbps: 105.2,
    packetLossRate: 0.0,
    totalPackets: 14200,
    encryption: {
      protocol: 'TLS 1.3 / ChaCha20',
      cipher: 'TLS_CHACHA20_POLY1305_SHA256',
      certIssuer: 'ISRG Root X1',
      certValidDays: 78,
    },
    whois: {
      asn: 'AS37100',
      asnOrg: 'Teraco Data Environments (Pty) Ltd',
      netName: 'TERACO-NAPAFRICA',
      cidr: '197.80.128.0/19',
      registrar: 'AFRINIC',
      registeredDate: '2010-04-18',
      updatedDate: '2024-07-12',
      abuseContact: 'abuse@teraco.co.za',
      reputationScore: 97.4,
      dnsServers: ['ns1.teraco.co.za', 'ns2.teraco.co.za'],
      orgAddress: 'Great Westerford, Main Rd, Rondebosch, Cape Town',
      statusComment: 'NAPAfrica Internet Exchange - 2Africa Subsea Terminal',
    },
    tracerouteHops: [
      { hopNumber: 1, ip: '192.168.1.1', hostname: 'fritz.box', latencyMs: 0.8, carrier: 'LAN Gateway', location: 'Local', status: 'ok' },
      { hopNumber: 2, ip: '62.155.242.74', hostname: 'f-ed5-i.F.DE.NET.DTAG.DE', latencyMs: 2.1, carrier: 'Deutsche Telekom', location: 'Frankfurt', status: 'ok' },
      { hopNumber: 3, ip: '195.229.2.14', hostname: 'mrs-wacs-cable.net', latencyMs: 32.1, carrier: 'WACS Cable System', location: 'Marseille', status: 'ok' },
      { hopNumber: 4, ip: '196.32.209.11', hostname: 'wacs-cpt-landing.za.net', latencyMs: 138.5, carrier: 'WACS West Africa', location: 'Yzerfontein Landing', status: 'ok' },
      { hopNumber: 5, ip: '197.80.128.4', hostname: 'cpt-ixp.teraco.co.za', latencyMs: 148.9, carrier: 'Teraco NAPAfrica', location: 'Cape Town', status: 'ok' },
    ],
  },
  {
    id: 'conn-lon-equinix',
    name: 'London Financial Equinix LD4',
    host: 'ld4-crossconnect.equinix.com',
    ip: '195.66.225.10',
    port: 443,
    protocol: 'WSS',
    type: 'p2p',
    city: 'London',
    country: 'Vereinigtes Königreich',
    countryCode: 'GB',
    lat: 51.5074,
    lng: -0.1278,
    status: 'active',
    latencyMs: 14.2,
    jitterMs: 0.3,
    rxKbps: 2410.8,
    txKbps: 980.2,
    packetLossRate: 0.0,
    totalPackets: 94500,
    encryption: {
      protocol: 'TLS 1.3 / Low-Latency FinTech',
      cipher: 'TLS_AES_256_GCM_SHA384',
      certIssuer: 'DigiCert Global Root CA',
      certValidDays: 280,
    },
    whois: {
      asn: 'AS8714',
      asnOrg: 'Equinix (UK) Limited',
      netName: 'EQUINIX-LD4',
      cidr: '195.66.224.0/20',
      registrar: 'RIPE NCC',
      registeredDate: '1998-05-12',
      updatedDate: '2025-01-08',
      abuseContact: 'abuse-ldn@equinix.com',
      reputationScore: 99.8,
      dnsServers: ['ns1.equinix.com', 'ns2.equinix.com'],
      orgAddress: '2 Buckingham Ave, Slough Trading Estate, London, UK',
      statusComment: 'LINX Peering & Cross-Connect Trading Hub',
    },
    tracerouteHops: [
      { hopNumber: 1, ip: '192.168.1.1', hostname: 'fritz.box', latencyMs: 0.7, carrier: 'LAN Gateway', location: 'Local', status: 'ok' },
      { hopNumber: 2, ip: '62.155.242.74', hostname: 'f-ed5-i.F.DE.NET.DTAG.DE', latencyMs: 2.1, carrier: 'Deutsche Telekom', location: 'Frankfurt', status: 'ok' },
      { hopNumber: 3, ip: '217.5.116.12', hostname: 'bru-b1-link.telia.net', latencyMs: 7.8, carrier: 'Arelion Channel Tunnel', location: 'Brüssel / Lille', status: 'ok' },
      { hopNumber: 4, ip: '195.66.225.10', hostname: 'ld4-crossconnect.equinix.com', latencyMs: 14.2, carrier: 'LINX Slough Hub', location: 'London Slough', status: 'ok' },
    ],
  },
];

// Helper to generate a live simulated packet
export function generateRandomPacket(connections: NetworkConnection[]): LivePacket {
  const conn = connections[Math.floor(Math.random() * connections.length)] || connections[0];
  const directions: ('IN' | 'OUT')[] = ['IN', 'IN', 'OUT'];
  const direction = directions[Math.floor(Math.random() * directions.length)];
  const flags = direction === 'IN' ? ['ACK', 'PSH'] : ['ACK', Math.random() > 0.6 ? 'SYN' : 'FIN'];
  const bytes = Math.floor(Math.random() * 1400) + 54;

  const hexSnippets = [
    '17 03 03 00 28 8f b2 c0 4a 19 88 d3 ... [TLS Record]',
    '48 54 54 50 2f 32 20 32 30 30 20 4f ... [HTTP/2 Status: 200]',
    '00 00 01 04 00 00 00 01 88 5f 87 49 ... [QUIC Frame 0x01]',
    '81 85 37 fa 21 3d 7f 9b 4d 52 14 c9 ... [WSS Masked Payload]',
    '08 00 20 00 01 00 00 00 00 00 00 00 ... [DNS PTR Response]',
  ];

  return {
    id: 'pkt-' + Math.random().toString(36).substring(2, 9),
    timestamp: new Date().toLocaleTimeString('de-DE', { hour12: false, hour: '2-digit', minute: '2-digit', second: '2-digit', fractionalSecondDigits: 3 }),
    connectionId: conn.id,
    targetHost: conn.host,
    protocol: conn.protocol,
    direction,
    bytes,
    flags,
    snippet: hexSnippets[Math.floor(Math.random() * hexSnippets.length)],
  };
}

// Function to resolve / trace a custom user-entered endpoint
export async function analyzeCustomEndpoint(query: string): Promise<NetworkConnection> {
  const cleanInput = query.trim().replace(/^https?:\/\//, '').split('/')[0].split(':')[0];
  
  // Real DNS query via Cloudflare DoH
  let resolvedIp = '104.21.48.112';
  try {
    const dohUrl = `https://cloudflare-dns.com/dns-query?name=${encodeURIComponent(cleanInput)}&type=A`;
    const res = await fetch(dohUrl, {
      headers: { Accept: 'application/dns-json' },
    });
    if (res.ok) {
      const data = await res.json();
      if (data.Answer && data.Answer.length > 0) {
        const aRecord = data.Answer.find((ans: { type: number; data: string }) => ans.type === 1);
        if (aRecord && aRecord.data) {
          resolvedIp = aRecord.data;
        }
      }
    }
  } catch (e) {
    console.warn('DoH lookup warning, using generated fallback IP', e);
  }

  // Hash-based coordinate generator if not known
  const hash = cleanInput.split('').reduce((acc, char) => acc + char.charCodeAt(0), 0);
  const knownLocations = [
    { city: 'Berlin', country: 'Deutschland', countryCode: 'DE', lat: 52.5200, lng: 13.4050, asn: 'AS24940 Hetzner Online GmbH', ping: 8.5 },
    { city: 'Helsinki', country: 'Finnland', countryCode: 'FI', lat: 60.1699, lng: 24.9384, asn: 'AS24940 Hetzner Finland', ping: 28.4 },
    { city: 'Dublin', country: 'Irland', countryCode: 'IE', lat: 53.3498, lng: -6.2603, asn: 'AS16509 Amazon Web Services', ping: 21.3 },
    { city: 'Zürich', country: 'Schweiz', countryCode: 'CH', lat: 47.3769, lng: 8.5417, asn: 'AS3303 Swisscom AG', ping: 11.2 },
    { city: 'New York', country: 'Vereinigte Staaten', countryCode: 'US', lat: 40.7128, lng: -74.0060, asn: 'AS396982 Google LLC', ping: 78.5 },
    { city: 'Toronto', country: 'Kanada', countryCode: 'CA', lat: 43.6532, lng: -79.3832, asn: 'AS577 Bell Canada', ping: 86.1 },
    { city: 'Stockholm', country: 'Schweden', countryCode: 'SE', lat: 59.3293, lng: 18.0686, asn: 'AS1257 Tele2 AB', ping: 24.2 },
    { city: 'Warschau', country: 'Polen', countryCode: 'PL', lat: 52.2297, lng: 21.0122, asn: 'AS5617 Orange Polska', ping: 18.9 },
  ];

  const loc = knownLocations[hash % knownLocations.length];
  const asnOrg = loc.asn.split(' ').slice(1).join(' ');

  const newConn: NetworkConnection = {
    id: 'conn-custom-' + Date.now(),
    name: cleanInput.toUpperCase() + ' Node',
    host: cleanInput,
    ip: resolvedIp,
    port: 443,
    protocol: 'HTTPS',
    type: 'api',
    city: loc.city,
    country: loc.country,
    countryCode: loc.countryCode,
    lat: loc.lat,
    lng: loc.lng,
    status: 'active',
    latencyMs: loc.ping + Number((Math.random() * 2).toFixed(1)),
    jitterMs: 0.8,
    rxKbps: 680.0,
    txKbps: 180.0,
    packetLossRate: 0.0,
    totalPackets: 2400,
    encryption: {
      protocol: 'TLS 1.3 / Verified',
      cipher: 'TLS_AES_256_GCM_SHA384',
      certIssuer: 'DigiCert / Let\'s Encrypt Public CA',
      certValidDays: 110,
    },
    whois: {
      asn: loc.asn.split(' ')[0],
      asnOrg: asnOrg,
      netName: cleanInput.replace(/[^a-zA-Z0-9]/g, '').toUpperCase() + '-NET',
      cidr: `${resolvedIp.split('.').slice(0, 3).join('.')}.0/24`,
      registrar: 'RIPE NCC / ICANN',
      registeredDate: '2016-04-10',
      updatedDate: '2024-11-01',
      abuseContact: `abuse@${cleanInput}`,
      reputationScore: 98.6,
      dnsServers: [`ns1.${cleanInput}`, `ns2.${cleanInput}`],
      orgAddress: `${loc.city}, ${loc.country}`,
      statusComment: 'Dynamisch registrierter und verifizierter Host Endpoint',
    },
    tracerouteHops: [
      { hopNumber: 1, ip: '192.168.1.1', hostname: 'fritz.box', latencyMs: 0.8, carrier: 'LAN Gateway', location: 'Local', status: 'ok' },
      { hopNumber: 2, ip: '62.155.242.74', hostname: 'f-ed5-i.F.DE.NET.DTAG.DE', latencyMs: 2.1, carrier: 'Deutsche Telekom', location: 'Frankfurt', status: 'ok' },
      { hopNumber: 3, ip: '80.150.170.8', hostname: 'core-de-cix.net', latencyMs: 4.5, carrier: 'DE-CIX Peering', location: 'Frankfurt IX', status: 'ok' },
      { hopNumber: 4, ip: `${resolvedIp.split('.').slice(0, 3).join('.')}.1`, hostname: `gw-${loc.city.toLowerCase()}.carrier.net`, latencyMs: Math.max(1.2, loc.ping - 2.5), carrier: asnOrg, location: loc.city, status: 'ok' },
      { hopNumber: 5, ip: resolvedIp, hostname: cleanInput, latencyMs: loc.ping, carrier: asnOrg, location: loc.city, status: 'ok' },
    ],
  };

  return newConn;
}
